version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper_container
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - off-coupon-network

  kafka-1:
    image: bitnami/kafka:latest
    container_name: kafka_1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_container:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_1:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
    networks:
      - off-coupon-network

  kafka-2:
    image: bitnami/kafka:latest
    container_name: kafka_2
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_container:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_2:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
    networks:
      - off-coupon-network

  kafka-3:
    image: bitnami/kafka:latest
    container_name: kafka_3
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_container:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_3:9094
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
    networks:
      - off-coupon-network

  kafka-exporter:
    image: danielqsj/kafka-exporter
    container_name: kafka-exporter
    command: [
      "--kafka.server=kafka_1:9092",
      "--kafka.server=kafka_2:9093",
      "--kafka.server=kafka_3:9094"
    ]
    ports:
      - 9308:9308
    networks:
      - off-coupon-network

  loki:
    image: grafana/loki:2.9.0
    container_name: loki_container
    ports:
      - "3100:3100"
    command:
      - -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml:ro
      - /Users/yurimjeon/wal:/wal
      - /Users/yurimjeon/loki/index:/loki/index
      - /Users/yurimjeon/loki/cache:/loki/cache
      - /Users/yurimjeon/loki/chunks:/loki/chunks
      - /Users/yurimjeon/loki/compactor:/loki/compactor
    user: "10001:10001"
    networks:
      - off-coupon-network

  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail_container
    volumes:
      - ./logs/user:/var/log/user:ro
      - ./logs/coupon:/var/log/coupon:ro
      - ./logs/issue-coupon:/var/log/issue-coupon:ro
      - ./logs/coupon-kafka:/var/log/coupon-kafka:ro
      - ./promtail-config.yaml:/etc/promtail/config.yaml:ro
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki
    networks:
      - off-coupon-network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter_container
    ports:
      - "9100:9100"
    restart: always
    networks:
      - off-coupon-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_container
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - kafka-exporter
      - node-exporter
    networks:
      - off-coupon-network

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - "3200:3200"
      - "9411:9411"
      - "4317:4317"
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data/blocks:/var/tempo/blocks
      - ./tempo-data/wal:/var/tempo/wal
      - ./tempo-data/generator:/var/tempo/generator
    command: -config.file=/etc/tempo.yaml
    networks:
      - off-coupon-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
      - tempo
    networks:
      - off-coupon-network

  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root1234!!
      MYSQL_DATABASE: sparta
    ports:
      - "3307:3306"
    networks:
      - off-coupon-network

  master:
    image: redis:latest
    container_name: redis-master
    volumes:
      - ./master.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6382:6379"
    networks:
      - off-coupon-network

  slave:
    image: redis:latest
    container_name: redis-slave
    volumes:
      - ./slave.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6383:6379"
    networks:
      - off-coupon-network

  sentinel-1:
    image: redis:latest
    container_name: redis-sentinel-1
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-server /usr/local/etc/redis/sentinel.conf --sentinel
    ports:
      - "5003:26379"
    depends_on:
      - master
    networks:
      - off-coupon-network

  sentinel-2:
    image: redis:latest
    container_name: redis-sentinel-2
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-server /usr/local/etc/redis/sentinel.conf --sentinel
    ports:
      - "5004:26379"
    depends_on:
      - master
    networks:
      - off-coupon-network

  sentinel-3:
    image: redis:latest
    container_name: redis-sentinel-3
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-server /usr/local/etc/redis/sentinel.conf --sentinel
    ports:
      - "5005:26379"
    depends_on:
      - master
    networks:
      - off-coupon-network

  config-server-module:
    image: config-server-image
    container_name: config-server-module-container
    ports:
      - "9000:9000"
    networks:
      - off-coupon-network

  eureka-server-module:
    image: eureka-server-image
    container_name: eureka-server-module-container
    ports:
      - "8761:8761"
    networks:
      - off-coupon-network

  gateway-server-module:
    image: gateway-server-image
    container_name: gateway-server-module-container
    ports:
      - "8080:8080"
    environment:
      EUREKA_SERVER_URI: http://admin:1234@eureka-server-module-container:8761/eureka/
    networks:
      - off-coupon-network

  user-module:
    image: user-image
    container_name: user-module-container
    ports:
      - "8081:8080"
    depends_on:
      - mysql
      - config-server-module
      - eureka-server-module
      - gateway-server-module
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/sparta
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234!!
      EUREKA_SERVER_URI: http://admin:1234@eureka-server-module-container:8761/eureka/
      SPRING_CONFIG_IMPORT: "optional:configserver:http://admin:1234@config-server-module-container:9000"
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - ./logs/user:/var/log/user
    networks:
      - off-coupon-network

  coupon-module:
    image: coupon-image
    container_name: coupon-module-container
    ports:
      - "8082:8080"
    depends_on:
      - mysql
      - config-server-module
      - eureka-server-module
      - gateway-server-module
    environment:
      SPRING_REDIS_HOST: redis-master
      SPRING_REDIS_PORT: 6379
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/sparta
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234!!
      EUREKA_SERVER_URI: http://admin:1234@eureka-server-module-container:8761/eureka/
      SPRING_CONFIG_IMPORT: "optional:configserver:http://admin:1234@config-server-module-container:9000"
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - ./logs/coupon:/var/log/coupon
    networks:
      - off-coupon-network

  issue-coupon-module:
    image: issue-coupon-image
    container_name: issue-coupon-module-container
    ports:
      - "8083:8080"
    depends_on:
      - mysql
      - zookeeper
      - kafka-1
      - kafka-2
      - kafka-3
      - config-server-module
      - eureka-server-module
      - gateway-server-module
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka_1:9092,kafka_2:9093,kafka_3:9094
      SPRING_REDIS_HOST: redis-master
      SPRING_REDIS_PORT: 6379
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/sparta
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234!!
      EUREKA_SERVER_URI: http://admin:1234@eureka-server-module-container:8761/eureka/
      SPRING_CONFIG_IMPORT: "optional:configserver:http://admin:1234@config-server-module-container:9000"
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - ./logs/issue-coupon:/var/log/issue-coupon
    networks:
      - off-coupon-network

  coupon-kafka-module:
    image: coupon-kafka-image
    container_name: coupon-kafka-module-container
    ports:
      - "8084:8080"
    depends_on:
      - mysql
      - zookeeper
      - kafka-1
      - kafka-2
      - kafka-3
      - config-server-module
      - eureka-server-module
      - gateway-server-module
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka_1:9092,kafka_2:9093,kafka_3:9094
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/sparta
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234!!
      EUREKA_SERVER_URI: http://admin:1234@eureka-server-module-container:8761/eureka/
      SPRING_CONFIG_IMPORT: "optional:configserver:http://admin:1234@config-server-module-container:9000"
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - ./logs/coupon-kafka:/var/log/coupon-kafka
    networks:
      - off-coupon-network

networks:
  off-coupon-network:
    driver: bridge
